steps:
  - ${{ if or(eq(variables['Agent.OS'], 'Darwin'), eq(variables['Agent.OS'], 'Linux')) }}:
    - bash: bash <(curl -s https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh)
      displayName: Artifacts Credential Provider
  - ${{ if eq(variables['Agent.OS'], 'Windows_NT') }}:
    - powershell: iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.ps1'))
      displayName: Artifacts Credential Provider
