parameters:
  Configuration: Release
  Verbosity: Normal
  DotNetVersion: "2.1.403"
  CakeVersion: "0.30.0"
  NuGetVersion: '4.7.1'
  name: ''
  dependsOn: ''
  vmImage: ''
  pushNuget: false
jobs:
  - job: ${{ parameters.name }}
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - template: ../gitversion/restore.yml
      - template: ../cake/install.yml
        parameters:
          CakeVersion: ${{ parameters.CakeVersion }}
          DotNetVersion: ${{ parameters.DotNetVersion }}
      - template: ../cake/run.yml
        parameters:
          Configuration: ${{ parameters.Configuration }}
          Verbosity: ${{ parameters.Verbosity }}
      - ${{ if eq(parameters.pushNuget, 'true') }}:
        - template: ../standard/dotnet-push.yml
