
parameters:
  Configuration: Release
  Verbosity: Normal
  DotNetVersion: "2.1.403"
  CakeVersion: "0.30.0"
  NuGetVersion: '4.7.1'
  FeedId: ''
  FeedUri: ''
jobs:
  - job: GitVersion
    pool:
      vmImage: "VS2017-Win2016"
    steps:
      - template: ../gitversion/store.yml
        parameters:
          NuGetVersion: ${{ parameters.NuGetVersion }}

  - template: cake-job.yml
      parameters:
        name: 'Linux'
        dependsOn: GitVersion
        vmImage: "Ubuntu-16.04"
        pushNuget: true
        FeedId: ${{ parameters.FeedId }}
        FeedUri: ${{ parameters.FeedUri }}
        Configuration: ${{ parameters.Configuration }}
        Verbosity: ${{ parameters.Verbosity }}
        CakeVersion: ${{ parameters.CakeVersion }}
        DotNetVersion: ${{ parameters.DotNetVersion }}
        NuGetVersion: ${{ parameters.NuGetVersion }}
