parameters:
  Configuration: Release
  Verbosity: Normal
  DotNetVersion: "2.2.300"
  CakeVersion: "0.33.0"
  NuGetVersion: "5.1.0"
  Script: 'cakefile.cake'
  Target: 'Default'
jobs:
  - job: GitVersion
    pool:
      vmImage: windows-2019
    steps:
      - template: ../gitversion/store.yml
        parameters:
          NuGetVersion: ${{ parameters.NuGetVersion }}

  - template: ./cake-job.yml
    parameters:
      name: 'macOS'
      dependsOn: GitVersion
      vmImage: "macOS-10.14"
      pushNuget: false
      Configuration: ${{ parameters.Configuration }}
      Verbosity: ${{ parameters.Verbosity }}
      CakeVersion: ${{ parameters.CakeVersion }}
      DotNetVersion: ${{ parameters.DotNetVersion }}
      NuGetVersion: ${{ parameters.NuGetVersion }}
      Script: ${{ parameters.Script }}
      Target: ${{ parameters.Target }}

  - template: ./cake-job.yml
    parameters:
      name: 'Linux'
      dependsOn: GitVersion
      vmImage: "Ubuntu-16.04"
      pushNuget: false
      Configuration: ${{ parameters.Configuration }}
      Verbosity: ${{ parameters.Verbosity }}
      CakeVersion: ${{ parameters.CakeVersion }}
      DotNetVersion: ${{ parameters.DotNetVersion }}
      NuGetVersion: ${{ parameters.NuGetVersion }}
      Script: ${{ parameters.Script }}
      Target: ${{ parameters.Target }}

  - template: ./cake-job.yml
    parameters:
      name: 'Windows'
      dependsOn: GitVersion
      vmImage: "windows-2019"
      pushNuget: true
      Configuration: ${{ parameters.Configuration }}
      Verbosity: ${{ parameters.Verbosity }}
      CakeVersion: ${{ parameters.CakeVersion }}
      DotNetVersion: ${{ parameters.DotNetVersion }}
      NuGetVersion: ${{ parameters.NuGetVersion }}
      Script: ${{ parameters.Script }}
      Target: ${{ parameters.Target }}
