
parameters:
  Configuration: Release
  Verbosity: Normal
  DotNet21Version: "2.1.801"
  DotNetVersion: "2.2.401"
  DotNet3Version: "3.0.100-preview8-013656"
  NuGetVersion: "5.2.0"
  BranchNameFix: false
  FeedId: ''
  NuGetSource: ''
  poolName: 'Default'
jobs:
  - job: GitVersion
    pool:
      name: ${{ parameters.poolName }}
    steps:
      - template: ../gitversion/store.yml
        parameters:
          NuGetVersion: ${{ parameters.NuGetVersion }}
          BranchNameFix: ${{ parameters.BranchNameFix }}

  - template: cake-job-private.yml
    parameters:
      name: 'Hosted'
      dependsOn: GitVersion
      poolName: ${{ parameters.poolName }}
      FeedId: ${{ parameters.FeedId }}
      NuGetSource: ${{ parameters.NuGetSource }}
      Configuration: ${{ parameters.Configuration }}
      Verbosity: ${{ parameters.Verbosity }}
      DotNet21Version: ${{ parameters.DotNet21Version }}
      DotNetVersion: ${{ parameters.DotNetVersion }}
      DotNet3Version: ${{ parameters.DotNet3Version }}
      NuGetVersion: ${{ parameters.NuGetVersion }}

  - job: Publish NuGet Packages
    pool:
      vmImage: "windows-latest"
    dependsOn:
      - Hosted
    steps:
      - download: current
        displayName: "Download NuGet Packages"
        artifact: 'Nupkg'
      - template: ../standard/nuget-push-feed.yml
        parameters:
          Artifacts: "$(Pipeline.Workspace)/Nupkg/"
          FeedId: ${{ parameters.FeedId }}
