
parameters:
  Configuration: Release
  Verbosity: Normal
  DotNetVersion: "2.1.403"
  CakeVersion: "0.30.0"
  NuGetVersion: '4.7.1'
  FeedId: ''
  poolName: ''
jobs:
  - job: GitVersion
    pool:
      vmImage: "VS2017-Win2016"
    steps:
      - template: ../gitversion/store.yml
        parameters:
          NuGetVersion: ${{ parameters.NuGetVersion }}

  - template: cake-job-private.yml
    parameters:
      name: 'Hosted'
      dependsOn: GitVersion
      poolName: ${{ parameters.poolName }}
      pushNuget: true
      FeedId: ${{ parameters.FeedId }}
      Configuration: ${{ parameters.Configuration }}
      Verbosity: ${{ parameters.Verbosity }}
      CakeVersion: ${{ parameters.CakeVersion }}
      DotNetVersion: ${{ parameters.DotNetVersion }}
      NuGetVersion: ${{ parameters.NuGetVersion }}