
parameters:
  Configuration: Release
  Verbosity: Normal
  DotNet21Version: "2.1.801"
  DotNetVersion: "2.2.401"
  DotNet3Version: "3.0.100-preview8-013656"
  NuGetVersion: "5.2.0"
  BranchNameFix: false
  FeedId: ''
  NuGetSource: ''
jobs:
  - job: GitVersion
    pool:
      vmImage: "windows-2019"
    steps:
      - template: ../gitversion/store.yml
        parameters:
          NuGetVersion: ${{ parameters.NuGetVersion }}
          BranchNameFix: ${{ parameters.BranchNameFix }}

  - template: nuke-job-private.yml
    parameters:
      name: 'Windows'
      dependsOn: GitVersion
      vmImage: "windows-2019"
      pushNuget: true
      FeedId: ${{ parameters.FeedId }}
      NuGetSource: ${{ parameters.NuGetSource }}
      Configuration: ${{ parameters.Configuration }}
      Verbosity: ${{ parameters.Verbosity }}
      DotNet21Version: ${{ parameters.DotNet21Version }}
      DotNetVersion: ${{ parameters.DotNetVersion }}
      DotNet3Version: ${{ parameters.DotNet3Version }}
      NuGetVersion: ${{ parameters.NuGetVersion }}
