parameters:
  Configuration: Release
  Verbosity: Normal
  DotNetSdk:
    - 2.2.x
    - 3.0.x
  NuGetVersion: "5.3.0"
  BranchNameFix: true
  Targets: "Default"
  EnableReleaseNotes: true
  GitHub: false
  GitHubPackages: false
  GithubAuthVariableGroup: ""
  MonoVersion: "6.4.0"
  MyGetPackages: false
  AuthNuGetFeeds: []
  NuGetConfig: 'NuGet.config'
  PublishNuGetPackages: 'Windows'
  Matrix:
    Windows:
      BuildName: "Windows"
      ImageName: "windows-latest"
    Linux:
      BuildName: "Linux"
      ImageName: "ubuntu-latest"
    macOS:
      BuildName: "macOS"
      ImageName: "macOS-latest"
  Steps:
    - template: ./default-nuke-steps.yml
jobs:
  - job: GitVersion
    pool:
      vmImage: windows-latest
    steps:
      - template: ../support/gitversion-store.yml
        parameters:
          BranchNameFix: ${{ parameters.BranchNameFix }}

  - template: ../support/publish-release.yml
    parameters:
      EnableReleaseNotes: ${{ parameters.EnableReleaseNotes }}
      GitHub: ${{ parameters.GitHub }}
      GitHubPackages: ${{ parameters.GitHubPackages }}
      GitHubAuthVariableGroup: ${{ parameters.GitHubAuthVariableGroup }}
      MyGetPackages: ${{ parameters.MyGetPackages }}
      NuGetVersion: ${{ parameters.NuGetVersion }}
      Postfix: " - ${{ parameters.PublishNuGetPackages }}"
      AuthNuGetFeeds: ${{ parameters.AuthNuGetFeeds }}

  - job: Build
    dependsOn:
      - ${{ if and(eq(parameters.EnableReleaseNotes, 'true'), eq(parameters.GitHub, 'true'), startsWith(variables['Build.SourceBranch'], 'refs/tags/v')) }}:
        - GitHub_Draft_Release
    variables:
      - ${{ if ne(parameters.GitHubAuthVariableGroup, '') }}:
        - group: ${{ parameters.GitHubAuthVariableGroup }}
    strategy:
      matrix: ${{ parameters.Matrix }}
    pool:
      vmImage: $(ImageName)
    steps:
      - template: ../support/mono.yml
        parameters:
          MonoVersion: ${{ parameters.MonoVersion }}
      - template: ../support/download-release-notes.yml
        parameters:
          EnableReleaseNotes: ${{ parameters.EnableReleaseNotes }}

      - template: ../support/gitversion-hack.yml
        parameters:
          BranchNameFix: ${{ parameters.BranchNameFix }}

      - template: ../support/install-dotnet.yml
        parameters:
          DotNetSdk: ${{ parameters.DotNetSdk }}
          AuthNuGetFeeds: ${{ parameters.AuthNuGetFeeds }}

      - task: DotNetCoreCLI@2
        displayName: "dotnet tool restore"
        inputs:
          command: custom
          custom: tool
          arguments: "restore"

      - task: DotNetCoreCLI@2
        displayName: 'dotnet restore'
        inputs:
          command: restore
          feedsToUse: config
          nugetConfigPath: ${{ parameters.NuGetConfig }}
          verbosityRestore: ${{ parameters.Verbosity }}

      - ${{ if eq(parameters.Steps, '') }}:
      - ${{ parameters.Steps }}

      - template: ../support/publish-artifacts.yml
        parameters:
          Configuration: ${{ parameters.Configuration }}
          Postfix: ' - $(BuildName)'
          PublishXUnit: false
          PublishVSTest: true
