parameters:
  Configuration: Release
  Verbosity: Normal
  DotNet21Version: "2.1.801"
  DotNetVersion: "2.2.401"
  DotNet3Version: "3.0.100-preview8-013656"
  NuGetVersion: "5.2.0"
  Targets: "Default"
  name: ""
  poolName: ""
  dependsOn: ""
  vmImage: ""
  pushNuget: false
  FeedId: ""
  NuGetSource: ""
  NuGetConfig: "NuGet.config"
  NuGetPackages: $(Pipeline.Workspace)/.nuget/packages
  NuGetFallbackPackages: ""
  RestorePackageConfig: false
jobs:
  - job: ${{ parameters.name }}
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      ${{ if ne(parameters.poolName, '') }}:
        name: ${{ parameters.poolName }}
      ${{ if ne(parameters.vmImage, '') }}:
        vmImage: ${{ parameters.vmImage }}
    # variables:
    #   - ${{ if and(ne(parameters.NuGetFallbackPackages, ''), eq(parameters.vmImage, 'macOS-10.14')) }}:
    #       - name: NUGET_FALLBACK_PACKAGES
    #       - value: "~/.nuget/packages"
    #   - ${{ if and(ne(parameters.NuGetFallbackPackages, ''), eq(parameters.vmImage, 'Ubuntu-16.04')) }}:
    #       - name: NUGET_FALLBACK_PACKAGES
    #       - value: "~/.nuget/packages"
    #   - ${{ if and(ne(parameters.NuGetFallbackPackages, ''), startsWith(parameters.vmImage, 'windows')) }}:
    #       - name: NUGET_FALLBACK_PACKAGES
    #       - value: '%userprofile%\.nuget\packages'
    #   - ${{ if ne(parameters.NuGetFallbackPackages, '') }}:
    #       - name: NUGET_FALLBACK_PACKAGES
    #       - value: ${{ parameters.NuGetFallbackPackages }}
    steps:
      - template: ../gitversion/restore.yml
      - template: ../standard/dotnet-restore.yml
      - ${{ if ne(parameters.NuGetSource, '') }}:
          - template: ../standard/nuget-source.yml
      - template: ../nuke/install.yml
        parameters:
          DotNet21Version: ${{ parameters.DotNet21Version }}
          DotNetVersion: ${{ parameters.DotNetVersion }}
          DotNet3Version: ${{ parameters.DotNet3Version }}
          NuGetVersion: ${{ parameters.NuGetVersion }}
          NuGetPackages: ${{ parameters.NuGetPackages }}
      - template: ../nuke/run.yml
        parameters:
          Configuration: ${{ parameters.Configuration }}
          Verbosity: ${{ parameters.Verbosity }}
          Targets: ${{ parameters.Targets }}
      - template: ../publish-artifacts.yml
        parameters:
          Configuration: ${{ parameters.Configuration }}
      - ${{ if eq(parameters.pushNuget, 'true') }}:
          - template: ../standard/nuget-push-feed.yml
            parameters:
              Artifacts: "$(Artifacts)/nuget/"
              FeedId: ${{ parameters.FeedId }}
