parameters:
  Configuration: Release
  Verbosity: Normal
  DotNetVersion: "2.2.301"
  DotNet3Version: "3.0.100-preview7-012821"
  NuGetVersion: "5.2.0"
  Targets: 'Default'
  name: ''
  poolName: ''
  dependsOn: ''
  vmImage: ''
  pushNuget: false
  FeedId: ''
  NuGetSource: ''
  NuGetConfig: 'NuGet.config'
  RestorePackageConfig: false
jobs:
  - job: ${{ parameters.name }}
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      ${{ if ne(parameters.poolName, '') }}:
        name: ${{ parameters.poolName }}
      ${{ if ne(parameters.vmImage, '') }}:
        vmImage: ${{ parameters.vmImage }}
    steps:
      - template: ../gitversion/restore.yml
      - template: ../standard/dotnet-restore.yml
      - ${{ if ne(parameters.NuGetSource, '') }}:
        - template: ../standard/nuget-source.yml
      - template: ../nuke/install.yml
        parameters:
          DotNetVersion: ${{ parameters.DotNetVersion }}
          DotNet3Version: ${{ parameters.DotNet3Version }}
          NuGetVersion: ${{ parameters.NuGetVersion }}
          RestorePackageConfig: ${{ parameters.RestorePackageConfig }}
      - template: ../nuke/run.yml
        parameters:
          Configuration: ${{ parameters.Configuration }}
          Verbosity: ${{ parameters.Verbosity }}
          Targets: ${{ parameters.Targets }}
      - template: ../publish-artifacts.yml
        parameters:
          Configuration: ${{ parameters.Configuration }}
      - ${{ if eq(parameters.pushNuget, 'true') }}:
        - template: ../standard/nuget-push-feed.yml
          parameters:
            Artifacts: "$(Artifacts)/nuget/"
            FeedId: ${{ parameters.FeedId }}
