parameters:
  Configuration: Release
  Verbosity: Normal
  DotNetVersion: "2.2.401"
  DotNet3Version: "3.0.100-preview7-012821"
  NuGetVersion: "5.2.0"
  Targets: 'Default'
  GitHub: false
  GitHubPackages: false
jobs:
  - job: GitVersion
    pool:
      vmImage: windows-2019
    steps:
      - template: ../gitversion/store.yml
        parameters:
          NuGetVersion: ${{ parameters.NuGetVersion }}

  - template: ./nuke-job.yml
    parameters:
      name: 'macOS'
      dependsOn: GitVersion
      vmImage: "macOS-10.14"
      pushNuget: false
      Configuration: ${{ parameters.Configuration }}
      Verbosity: ${{ parameters.Verbosity }}
      DotNetVersion: ${{ parameters.DotNetVersion }}
      DotNet3Version: ${{ parameters.DotNet3Version }}
      NuGetVersion: ${{ parameters.NuGetVersion }}
      Targets: ${{ parameters.Targets }}

  - template: ./nuke-job.yml
    parameters:
      name: 'Linux'
      dependsOn: GitVersion
      vmImage: "Ubuntu-16.04"
      pushNuget: false
      Configuration: ${{ parameters.Configuration }}
      Verbosity: ${{ parameters.Verbosity }}
      DotNetVersion: ${{ parameters.DotNetVersion }}
      DotNet3Version: ${{ parameters.DotNet3Version }}
      NuGetVersion: ${{ parameters.NuGetVersion }}
      Targets: ${{ parameters.Targets }}

  - template: ./nuke-job.yml
    parameters:
      name: 'Windows'
      dependsOn: GitVersion
      vmImage: "windows-2019"
      pushNuget: false
      Configuration: ${{ parameters.Configuration }}
      Verbosity: ${{ parameters.Verbosity }}
      DotNetVersion: ${{ parameters.DotNetVersion }}
      DotNet3Version: ${{ parameters.DotNet3Version }}
      NuGetVersion: ${{ parameters.NuGetVersion }}
      Targets: ${{ parameters.Targets }}

  - ${{ if ne(variables['System.PullRequest.IsFork'], 'true') }}:
    - job: GitHub_Draft_Release
      pool:
        vmImage: "windows-2019"
      dependsOn:
        - GitVersion
      steps:
        # - checkout: none
        - template: ../gitversion/restore.yml
        - ${{ if eq(parameters.GitHub, 'true') }}:
          - template: ../standard/github-draft-release.yml
            parameters:
              DotNetVersion: ${{ parameters.DotNetVersion }}
              DotNet3Version: ${{ parameters.DotNet3Version }}

    - job: Publish
      pool:
        vmImage: "windows-2019"
      dependsOn:
        - macOS
        - Linux
        - Windows
        - GitHub_Draft_Release
      steps:
        # - checkout: none
        - task: DownloadBuildArtifacts@0
          displayName: "Download NuGet Packages"
          inputs:
            specificBuildWithTriggering: true
            downloadType: single
            artifactName: 'Nupkg - Windows'
            downloadPath: $(Build.ArtifactStagingDirectory)/nuget/
        - template: ../standard/nuget-push.yml
          parameters:
            NuGetVersion: ${{ parameters.NuGetVersion }}
            Verbosity: ${{ parameters.Verbosity }}
            GitHubPackages: ${{ parameters.GitHubPackages }}

    - job: GitHub_Release
      pool:
        vmImage: "windows-2019"
      dependsOn:
        - macOS
        - Linux
        - Windows
        - GitHub_Draft_Release
      steps:
        # - checkout: none
        - template: ../gitversion/restore.yml
        - ${{ if eq(parameters.GitHub, 'true') }}:
          - template: ../standard/github-release.yml
            parameters:
              DotNetVersion: ${{ parameters.DotNetVersion }}
              DotNet3Version: ${{ parameters.DotNet3Version }}


