parameters:
  MyGetFeed: "myget.org"
  MyGetPackages: false
  NuGetFeed: "nuget.org"
  GitHubFeed: "github.nuget"
  GitHubPackages: false
  AzureDevOpsFeed: ''
  AzureDevOpsPackages: false
  AzureDevOpsPreviewFeed: ''
  AzureDevOpsPreviewPackages: false
  NuGetVersion: '5.7.0'
  PublishNuGetPackagesFromArtifact: ''
  AuthNuGetFeeds: []

jobs:
  - ${{ if and(ne(parameters.PublishNuGetPackagesFromArtifact, ''), ne(variables['System.PullRequest.IsFork'], 'true')) }}:
    - job: Publish_NuGet_Packages
      displayName: "Publish NuGet Packages"
      pool:
        vmImage: "windows-latest"
      dependsOn:
        - Build
      steps:
        - checkout: none
        - download: current
          displayName: "Download NuGet Packages"
          artifact: "${{ parameters.PublishNuGetPackagesFromArtifact }}"
        - template: ../support/nuget-push.yml
          parameters:
            Artifacts: "$(Pipeline.Workspace)"
            NuGetVersion: ${{ parameters.NuGetVersion }}
            MyGetFeed: ${{ parameters.MyGetFeed }}
            MyGetPackages: ${{ parameters.MyGetPackages }}
            NuGetFeed: ${{ parameters.NuGetFeed }}
            GitHubFeed: ${{ parameters.GitHubFeed }}
            GitHubPackages: ${{ parameters.GitHubPackages }}
            AzureDevOpsFeed: ${{ parameters.AzureDevOpsFeed }}
            AzureDevOpsPackages: ${{ parameters.AzureDevOpsPackages }}
            AzureDevOpsPreviewFeed: ${{ parameters.AzureDevOpsPreviewFeed }}
            AzureDevOpsPreviewPackages: ${{ parameters.AzureDevOpsPreviewPackages }}
  # - ${{ if and(or(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'), eq(variables['Build.SourceBranch'], 'refs/heads/master')), ne(variables['System.PullRequest.IsFork'], 'true')) }}:
