parameters:
  EnableReleaseNotes: false
  GitHubPackages: false
  MyGetPackages: false
  NuGetVersion: '5.4.0'
  PublishNuGetPackagesFromArtifact: ''
  AuthNuGetFeeds: []

jobs:
  - ${{ if and(or(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'), eq(variables['Build.SourceBranch'], 'refs/heads/master')), ne(variables['System.PullRequest.IsFork'], 'true')) }}:
    - ${{ if ne(parameters.PublishNuGetPackagesFromArtifact, '') }}:
      - job: Publish_NuGet_Packages
        displayName: "Publish NuGet Packages"
        pool:
          vmImage: "windows-latest"
        dependsOn:
          - Build
        steps:
          - checkout: none
          - download: current
            displayName: "Download NuGet Packages"
            artifact: "${{ parameters.PublishNuGetPackagesFromArtifact }}"
          - template: ../support/nuget-push.yml
            parameters:
              Artifacts: "$(Pipeline.Workspace)"
              NuGetVersion: ${{ parameters.NuGetVersion }}
              GitHubPackages: ${{ parameters.GitHubPackages }}
              MyGetPackages: ${{ parameters.MyGetPackages }}
